name: manage-azure-policy-48720971
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Cache_for_Redis_should_disable_public_network_access_470baccb-7e51-4549-8b1a-3e5be069f663/**'
#      - 'policies/Managed_disks_should_disable_public_network_access_8405fdab-1faf-48aa-b702-999c9c172094/**'
#      - 'policies/Configure_SQL_servers_to_have_auditing_enabled_to_Log_Analytics_workspace_25da7dfb-0666-4a15-a8f5-402127efd8bb/**'
#      - 'policies/Configure_Azure_SQL_database_servers_diagnostic_settings_to_Log_Analytics_workspace_7ea8a143-05e3-4553-abfe-f56bef8b0b70/**'
#      - 'policies/Transparent_Data_Encryption_on_SQL_databases_should_be_enabled_17k78e20-9358-41c9-923c-fb736d382a12/**'
#      - 'policies/App_Services_should_disable_public_network_access_63a0ac64-5d5f-4569-8a3d-df67cc1ce9d7/**'
#      - .github/workflows/manage-azure-policy-48720971.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_48720971}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Cache_for_Redis_should_disable_public_network_access_470baccb-7e51-4549-8b1a-3e5be069f663/**
          policies/Managed_disks_should_disable_public_network_access_8405fdab-1faf-48aa-b702-999c9c172094/**
          policies/Configure_SQL_servers_to_have_auditing_enabled_to_Log_Analytics_workspace_25da7dfb-0666-4a15-a8f5-402127efd8bb/**
          policies/Configure_Azure_SQL_database_servers_diagnostic_settings_to_Log_Analytics_workspace_7ea8a143-05e3-4553-abfe-f56bef8b0b70/**
          policies/Transparent_Data_Encryption_on_SQL_databases_should_be_enabled_17k78e20-9358-41c9-923c-fb736d382a12/**
          policies/App_Services_should_disable_public_network_access_63a0ac64-5d5f-4569-8a3d-df67cc1ce9d7/**
