name: manage-azure-policy-13fe20f2
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Key_vaults_should_have_purge_protection_enabled_0b60c0b2-2dc2-4e1c-b5c9-abbed971de53/**'
#      - 'policies/Azure_Defender_for_Key_Vault_should_be_enabled_0e6763cc-5078-4e64-889d-ff4d9a839047/**'
#      - 'policies/Key_vaults_should_have_soft_delete_enabled_1e66c121-a66a-4b1f-9b83-0fd99bf0fc2d/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Log_Analytics_workspace_bef3f64c-5290-43b7-85b0-9b254eef4c47/**'
#      - 'policies/Storage_account_keys_should_not_be_expired_044985bb-afe1-42cd-8a36-9d5d42424537/**'
#      - 'policies/_Preview_Storage_account_public_access_should_be_disallowed_4fa4b6c0-31ca-4c0d-b10d-24b96f62a751/**'
#      - 'policies/Storage_accounts_should_use_customer-managed_key_for_encryption_6fac406b-40ca-413b-bf8e-0bf964659c25/**'
#      - 'policies/_Preview_Configure_backup_for_blobs_on_storage_accounts_with_a_given_tag_to_an_existing_backup_vault_in_the_same_region_615b01c4-d565-4f6f-8c6e-d130268e3a1a/**'
#      - 'policies/Configure_diagnostic_settings_for_storage_accounts_to_Log_Analytics_workspace_6f8f98a4-f108-47cb-8e98-91a0d85cd474/**'
#      - 'policies/Storage_accounts_should_restrict_network_access_using_virtual_network_rules_2a1a9cdf-e04d-429a-8416-3bfb72a1b26f/**'
#      - 'policies/Secure_transfer_to_storage_accounts_should_be_enabled_404c3081-a854-4457-ae30-26a93ef643f9/**'
#      - 'policies/Require_a_tag_and_its_value_on_resources_1e30110a-5ceb-460c-a204-c1c3969c6d62/**'
#      - 'policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/**'
#      - 'policies/Not_allowed_resource_types_6c112d4e-5bc7-47ae-a041-ea2d9dccd749/**'
#      - 'policies/Configure_Azure_Activity_logs_to_stream_to_specified_Log_Analytics_workspace_2465583e-4e78-4c15-b6be-a36cbc7c8b0f/**'
#      - 'policies/Enable_Azure_Security_Center_on_your_subscription_ac076320-ddcf-4066-b451-6154267e8ad2/**'
#      - 'policies/Configure_managed_disks_to_disable_public_network_access_8426280e-b5be-43d9-979e-653d12a08638/**'
#      - 'policies/Managed_disks_should_be_double_encrypted_with_both_platform-managed_and_customer-managed_keys_ca91455f-eace-4f96-be59-e6e2c35b4816/**'
#      - 'policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**'
#      - 'policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**'
#      - 'policies/Deploy_-_Configure_Log_Analytics_extension_to_be_enabled_on_Windows_virtual_machines_0868462e-646c-4fe3-9ced-a733534b6a2c/**'
#      - 'policies/Adaptive_network_hardening_recommendations_should_be_applied_on_internet_facing_virtual_machines_08e6af2d-db70-460a-bfe9-d5bd474ba9d6/**'
#      - 'policies/Management_ports_should_be_closed_on_your_virtual_machines_22730e10-96f6-4aac-ad84-9383d35b5917/**'
#      - 'policies/IP_Forwarding_on_your_virtual_machine_should_be_disabled_bd352bd5-2853-4985-bf0d-73806b4a5744/**'
#      - 'policies/Network_interfaces_should_disable_IP_forwarding_88c0b9da-ce96-4b03-9635-f29a937e2900/**'
#      - 'policies/Microsoft_Defender_for_Containers_should_be_enabled_1c988dd6-ade4-430f-a608-2a3e5b0a6d38/**'
#      - 'policies/Public_network_access_should_be_disabled_for_Container_registries_0fdf0491-d080-4575-b627-ad0e843cba0f/**'
#      - 'policies/Deploy_network_watcher_when_virtual_networks_are_created_a9b99dd8-06c5-4317-8629-9d86a3c6e7d9/**'
#      - 'policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_1b8ca024-1d5c-4dec-8995-b1a932b41780/**'
#      - 'policies/Azure_SignalR_Service_should_disable_public_network_access_21a9766a-82a5-4747-abb5-650b6dbba6d0/**'
#      - 'policies/Public_network_access_should_be_disabled_for_PostgreSQL_servers_b52376f7-9612-48a1-81cd-1ffe4b61032c/**'
#      - 'policies/Public_network_access_should_be_disabled_for_MySQL_servers_d9844e8a-1437-4aeb-a32c-0c992f056095/**'
#      - 'policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_of_1.2_a8793640-60f7-487c-b5c3-1d37215905c4/**'
#      - 'policies/App_Service_Environment_should_disable_TLS_1.0_and_1.1_d6545c6b-dd9d-4265-91e6-0b451e2f1c50/**'
#      - .github/workflows/manage-azure-policy-13fe20f2.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_13fe20f2}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Key_vaults_should_have_purge_protection_enabled_0b60c0b2-2dc2-4e1c-b5c9-abbed971de53/**
          policies/Azure_Defender_for_Key_Vault_should_be_enabled_0e6763cc-5078-4e64-889d-ff4d9a839047/**
          policies/Key_vaults_should_have_soft_delete_enabled_1e66c121-a66a-4b1f-9b83-0fd99bf0fc2d/**
          policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Log_Analytics_workspace_bef3f64c-5290-43b7-85b0-9b254eef4c47/**
          policies/Storage_account_keys_should_not_be_expired_044985bb-afe1-42cd-8a36-9d5d42424537/**
          policies/_Preview_Storage_account_public_access_should_be_disallowed_4fa4b6c0-31ca-4c0d-b10d-24b96f62a751/**
          policies/Storage_accounts_should_use_customer-managed_key_for_encryption_6fac406b-40ca-413b-bf8e-0bf964659c25/**
          policies/_Preview_Configure_backup_for_blobs_on_storage_accounts_with_a_given_tag_to_an_existing_backup_vault_in_the_same_region_615b01c4-d565-4f6f-8c6e-d130268e3a1a/**
          policies/Configure_diagnostic_settings_for_storage_accounts_to_Log_Analytics_workspace_6f8f98a4-f108-47cb-8e98-91a0d85cd474/**
          policies/Storage_accounts_should_restrict_network_access_using_virtual_network_rules_2a1a9cdf-e04d-429a-8416-3bfb72a1b26f/**
          policies/Secure_transfer_to_storage_accounts_should_be_enabled_404c3081-a854-4457-ae30-26a93ef643f9/**
          policies/Require_a_tag_and_its_value_on_resources_1e30110a-5ceb-460c-a204-c1c3969c6d62/**
          policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/**
          policies/Not_allowed_resource_types_6c112d4e-5bc7-47ae-a041-ea2d9dccd749/**
          policies/Configure_Azure_Activity_logs_to_stream_to_specified_Log_Analytics_workspace_2465583e-4e78-4c15-b6be-a36cbc7c8b0f/**
          policies/Enable_Azure_Security_Center_on_your_subscription_ac076320-ddcf-4066-b451-6154267e8ad2/**
          policies/Configure_managed_disks_to_disable_public_network_access_8426280e-b5be-43d9-979e-653d12a08638/**
          policies/Managed_disks_should_be_double_encrypted_with_both_platform-managed_and_customer-managed_keys_ca91455f-eace-4f96-be59-e6e2c35b4816/**
          policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**
          policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**
          policies/Deploy_-_Configure_Log_Analytics_extension_to_be_enabled_on_Windows_virtual_machines_0868462e-646c-4fe3-9ced-a733534b6a2c/**
          policies/Adaptive_network_hardening_recommendations_should_be_applied_on_internet_facing_virtual_machines_08e6af2d-db70-460a-bfe9-d5bd474ba9d6/**
          policies/Management_ports_should_be_closed_on_your_virtual_machines_22730e10-96f6-4aac-ad84-9383d35b5917/**
          policies/IP_Forwarding_on_your_virtual_machine_should_be_disabled_bd352bd5-2853-4985-bf0d-73806b4a5744/**
          policies/Network_interfaces_should_disable_IP_forwarding_88c0b9da-ce96-4b03-9635-f29a937e2900/**
          policies/Microsoft_Defender_for_Containers_should_be_enabled_1c988dd6-ade4-430f-a608-2a3e5b0a6d38/**
          policies/Public_network_access_should_be_disabled_for_Container_registries_0fdf0491-d080-4575-b627-ad0e843cba0f/**
          policies/Deploy_network_watcher_when_virtual_networks_are_created_a9b99dd8-06c5-4317-8629-9d86a3c6e7d9/**
          policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_1b8ca024-1d5c-4dec-8995-b1a932b41780/**
          policies/Azure_SignalR_Service_should_disable_public_network_access_21a9766a-82a5-4747-abb5-650b6dbba6d0/**
          policies/Public_network_access_should_be_disabled_for_PostgreSQL_servers_b52376f7-9612-48a1-81cd-1ffe4b61032c/**
          policies/Public_network_access_should_be_disabled_for_MySQL_servers_d9844e8a-1437-4aeb-a32c-0c992f056095/**
          policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_of_1.2_a8793640-60f7-487c-b5c3-1d37215905c4/**
          policies/App_Service_Environment_should_disable_TLS_1.0_and_1.1_d6545c6b-dd9d-4265-91e6-0b451e2f1c50/**
