name: manage-azure-policy-458211af
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Vulnerability_assessment_should_be_enabled_on_your_SQL_servers_ef2a8f2a-b3d9-49cd-a8a8-9a3aaaf647d9/**'
#      - 'policies/Allowed_resource_types_a08ec900-254a-4555-9bf5-e42af04b5c5c/**'
#      - .github/workflows/manage-azure-policy-458211af.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_458211af}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Vulnerability_assessment_should_be_enabled_on_your_SQL_servers_ef2a8f2a-b3d9-49cd-a8a8-9a3aaaf647d9/**
          policies/Allowed_resource_types_a08ec900-254a-4555-9bf5-e42af04b5c5c/**
